### PR TITLE
fix: skip connection check in case there is no port exposed + map old port format to new format

### LINKED ISSUE #155: docker-compose parsing: convert "oldschool" port format to new port format
extract from: https://github.com/erikengervall/dockest/issues/140

> A Postgres service in docker-compose.yml must use a full ports format with target and published, not something like 5432:5432. If a wrong format is used, the result is connection timeout (healthcheck) without explanation which is bewildering.

We should probably convert the old-school format "port:port" to -> the new format `{ "published": port, "target": port }` , so that the check here does not fail with weird reasons.

https://github.com/erikengervall/dockest/blob/7da1dda02bebd7734c73a186c73aa010a5bc711b/packages/dockest/src/run/waitForServices/checkConnection.ts

I got the same report from a co-worker in Slack:

>  cannot get even the simplest example to work with dockest. The readiness check for redis is timing out although I configured it with the default example and the port 6379 is specified.
[Check Connection] Timeout in 9s (localhost:undefined)

### PR DESCRIPTION
**Pull request by n1ru4l**
Should probably also add an option that allows skipping the connection check.

Closes #155

### CODE REVIEW

File: packages/dockest/src/utils/selectPortMapping.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+import { DockerComposePortFormat } from '../@types'
+
+export const selectPortMapping = (input: DockerComposePortFormat) => {
+  if (typeof input !== 'string') return input
+  const [published, target] = input.split(':')
+  return { published: parseInt(published, 10), target: parseInt(target, 10) }
+}
```
Comment (erikengervall) [inline packages/dockest/src/utils/selectPortMapping.ts]: I'd love to see some unit tests for this piece of code

Comment (n1ru4l) [reply packages/dockest/src/utils/selectPortMapping.ts]: done 👌
